name: Deploy to neocities

on:
  push:
    branches:
      - main

concurrency:
  group: deploy-to-neocities
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # The checkout step copies your repo into the action runner. Important!
      - uses: actions/checkout@v4

      # Instala Jekyll e dependências
      - name: Install Jekyll dependencies
        run: |
          gem install bundler --user-install
          export PATH="$HOME/.gem/ruby/3.2.0/bin:$PATH"
          bundle install

      # Gera o site na pasta _site
      - name: Build Jekyll site
        run: bundle exec jekyll build
        env:
          JEKYLL_ENV: production

      # Prepara a pasta public para o deploy
      - name: Prepare public folder
        run: |
          rm -rf public
          mkdir public
          cp -r _site/* public/

      # When the dist_dir is ready, deploy it to neocities
      - name: Deploy to neocities
        uses: bcomnes/deploy-to-neocities@v3
        with:
          api_key: ${{ secrets.NEOCITIES_API_TOKEN }}
          cleanup: false
          neocities_supporter: false
          preview_before_deploy: true
          dist_dir: public
